/*
 * kernel/lib/backtrace.c
 * Frame-pointer backtrace + in-kernel symbol table lookup (Phase A steps 11-12).
 *
 * The walker relies on -fno-omit-frame-pointer (COMMON_FLAGS): every C frame
 * chains [fp] = caller fp, [fp+8] = return address, identically on amd64
 * (rbp) and aarch64 (x29).  Assembly boundaries (isr_stubs.S, exception.S,
 * context.S, syscall.S) do not build frames, so the walk is seeded from the
 * exception frame's pc/fp — never from the handler's own frame — and stops at
 * the first frame that leaves the validated ranges.  -O2 tail-calls may merge
 * a frame; an occasionally skipped entry is accepted.
 *
 * Symbolization uses the .ksyms blob generated by tools/gen_ksyms.sh from
 * `nm -n` of the first-pass link and linked into .rodata on the second pass:
 *
 *     u64  count
 *     u64  addrs[count]       (link addresses, ascending)
 *     u32  name_offs[count]   (offsets into the names blob)
 *     char names[]            (NUL-terminated, in table order)
 *
 * The section is ALLOC and placed in .rodata so it survives the aarch64
 * `objcopy -O binary kernel.bin` — that is the only way the running aarch64
 * image gets live symbolization.  Link address == runtime address on both
 * arches (identity-mapped kernel), so lookup is a plain binary search.
 * When the blob is absent (first-pass link), addresses print raw.
 *
 * Everything here is fault-context safe: fault_printf output only, every
 * dereference is bounds-checked first, and a residual bad read is converted
 * into a clean stop by the fault_enter() depth guard of the dispatcher.
 */
#include <kernel/fault.h>
#include <kernel/printk.h>
#include <kernel/types.h>

/* Linker-script symbols (both kernel.ld files) */
extern char __ksyms_start[];
extern char __ksyms_end[];
extern char __kernel_start[];
extern char _etext[];
extern char __kernel_end[];

#define BACKTRACE_MAX_FRAMES 24

/* Plausible-RAM ceiling for frame pointers: kernel stacks (boot stacks in
 * .bss, per-task stacks from the PMM) all live above the kernel image; 8GB
 * over __kernel_end covers every supported -m size while filtering wild fps. */
#define FP_RANGE_LIMIT (8ULL << 30)

static int text_addr_valid(uint64_t pc) {
  return pc >= (uint64_t)(uintptr_t)__kernel_start &&
         pc < (uint64_t)(uintptr_t)_etext;
}

static int fp_addr_valid(uint64_t fp) {
  if (fp == 0 || (fp & 7) != 0)
    return 0;
  if (fp < (uint64_t)(uintptr_t)__kernel_start)
    return 0;
  if (fp > (uint64_t)(uintptr_t)__kernel_end + FP_RANGE_LIMIT)
    return 0;
  return 1;
}

const char *ksym_lookup(uint64_t addr, uint64_t *off) {
  const char *blob = __ksyms_start;
  uint64_t blob_size = (uint64_t)(__ksyms_end - __ksyms_start);

  if (blob_size < 16)
    return NULL; /* no table linked (first-pass build) */

  uint64_t count = *(const uint64_t *)blob;
  const uint64_t *addrs = (const uint64_t *)(blob + 8);
  const uint32_t *name_offs = (const uint32_t *)(blob + 8 + count * 8);
  const char *names = (const char *)(blob + 8 + count * 8 + count * 4);

  /* Sanity: a corrupt header must not send us walking wild memory. */
  if (count == 0 || count > blob_size / 12 ||
      (const char *)names > __ksyms_end)
    return NULL;
  if (!text_addr_valid(addr))
    return NULL;

  /* Binary search: greatest table address <= addr. */
  uint64_t lo = 0, hi = count;
  while (lo < hi) {
    uint64_t mid = lo + (hi - lo) / 2;
    if (addrs[mid] <= addr)
      lo = mid + 1;
    else
      hi = mid;
  }
  if (lo == 0)
    return NULL;
  lo--;

  const char *name = names + name_offs[lo];
  if (name >= __ksyms_end)
    return NULL;
  if (off)
    *off = addr - addrs[lo];
  return name;
}

static void backtrace_emit(int idx, uint64_t pc) {
  uint64_t off = 0;
  const char *name = ksym_lookup(pc, &off);
  if (name)
    fault_printf("  #%-2d %016lx %s+0x%lx\n", idx, pc, name, off);
  else
    fault_printf("  #%-2d %016lx\n", idx, pc);
}

/*
 * backtrace_regs - walk and print the call chain starting at pc/fp.
 *
 * Seed from an exception frame (regs->rip/regs->rbp on amd64,
 * frame->elr/frame->regs[29] on aarch64) or from the current context via
 * backtrace_here().  Output goes through fault_printf — callable from any
 * fault path.
 */
void backtrace_regs(uint64_t pc, uint64_t fp) {
  fault_printf("Backtrace (fp chain, max %d):\n", BACKTRACE_MAX_FRAMES);
  backtrace_emit(0, pc);

  for (int i = 1; i < BACKTRACE_MAX_FRAMES; i++) {
    if (!fp_addr_valid(fp))
      break;
    uint64_t next_fp = *(const uint64_t *)fp;
    uint64_t ret = *(const uint64_t *)(fp + 8);
    if (!text_addr_valid(ret))
      break;
    backtrace_emit(i, ret);
    if (next_fp <= fp) /* frames must strictly grow toward the stack base */
      break;
    fp = next_fp;
  }
}

/*
 * backtrace_here - backtrace of the current call site (e.g. from panic()).
 */
void backtrace_here(void) {
  backtrace_regs((uint64_t)(uintptr_t)__builtin_return_address(0),
                 (uint64_t)(uintptr_t)__builtin_frame_address(0));
}
